#!/usr/bin/env python3
"""Regenerate scripts/data/*.txt from a checkout of the FRLG+ source.

    python3 tools/generate_tables.py --repo ../FRLG-Plus

Every table the extractor reads is produced here, so nothing in scripts/data is
hand-written any more. Each file starts with a header naming the source files it
came from. Run it again after pulling a new FRLG+ version, then run the tests.
"""
from __future__ import annotations

import argparse
import datetime
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import cparse  # noqa: E402
from cparse import Consts, read_array_entries, read_flat_list, read_name_table, read_struct_table  # noqa: E402

TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
# This file lives in shared/tools/ in the source repo and is vendored into the
# skill package as tools/. Either way the tables go to the skill's scripts/data.
_PARENT = os.path.dirname(TOOLS_DIR)
if os.path.basename(_PARENT) == "shared":
    SKILL_DIR = os.path.join(os.path.dirname(_PARENT), "skills", "frlg-save-extractor")
else:
    SKILL_DIR = _PARENT
DATA_DIR = os.path.join(SKILL_DIR, "scripts", "data")
OUT_DIR = DATA_DIR          # main() repoints this for --game vanilla

# Files each game's tables are parsed out of. The vanilla decomp generates
# map_groups.h and region_map_sections.h at build time, so a fresh checkout does
# not have them, which is why the vanilla run emits the layout only.
REQUIRED = {
    "frlgplus": ["include/global.h", "include/constants/global.h",
                 "include/constants/region_map_sections.h", "include/constants/map_groups.h"],
    # Everything compute_layout reads. A tree missing one is refused by name here
    # rather than dying later on a KeyError, since the constants loop skips quietly.
    "vanilla": ["include/global.h", "include/save.h", "include/pokemon_storage_system.h",
                # constants, in the order they must load: flags.h needs opponents.h's
                # MAX_TRAINERS_COUNT already defined
                "include/constants/global.h", "include/constants/items.h",
                "include/constants/species.h", "include/constants/game_stat.h",
                "include/constants/opponents.h", "include/constants/vars.h",
                "include/constants/flags.h"],
}

GROWTH_CODES = {"GROWTH_MEDIUM_FAST": "MF", "GROWTH_ERRATIC": "ER", "GROWTH_FLUCTUATING": "FL",
                "GROWTH_MEDIUM_SLOW": "MS", "GROWTH_FAST": "F", "GROWTH_SLOW": "S"}
TYPE_NAMES = {0: "Normal", 1: "Fighting", 2: "Flying", 3: "Poison", 4: "Ground", 5: "Rock", 6: "Bug",
              7: "Ghost", 8: "Steel", 9: "Mystery", 10: "Fire", 11: "Water", 12: "Grass", 13: "Electric",
              14: "Psychic", 15: "Ice", 16: "Dragon", 17: "Dark", 255: "None"}
ENCOUNTER_METHODS = {"LandMons": "grass", "WaterMons": "surf", "RockSmashMons": "rock smash",
                     "FishingMons": "fishing"}


# ---------------------------------------------------------------- display names
def titlecase(s):
    """ALL-CAPS game text -> Title Case, leaving apostrophes and symbols alone."""
    out, boundary = [], True
    for ch in s:
        if ch.isalpha():
            out.append(ch.upper() if boundary else ch.lower())
            boundary = False
        else:
            out.append(ch)
            boundary = ch != "'"
    return "".join(out)


def _normalise(s):
    return re.sub(r"[^0-9a-z♀♂]", "", s.lower()).replace("é", "e")


class Display:
    """Applies tools/display_names.json, refusing any override that renames."""

    def __init__(self, path):
        with open(path, encoding="utf-8") as f:
            self.tables = json.load(f)
        self.used = set()

    def name(self, group, const, game_name):
        override = self.tables.get(group, {}).get(const)
        if override is None:
            if re.fullmatch(r"(TM|HM)\d\d", game_name):
                return game_name
            return titlecase(game_name)
        self.used.add((group, const))
        if _normalise(override) != _normalise(game_name):
            raise SystemExit(f"display_names.json: {group}/{const} says {override!r} but the repo "
                             f"calls it {game_name!r} — overrides may only change capitalisation.")
        return override

    def unused(self):
        return [f"{g}/{k}" for g, t in self.tables.items() if isinstance(t, dict)
                for k in t if (g, k) not in self.used]


# ---------------------------------------------------------------- writing
def write_table(name, header, rows):
    path = os.path.join(OUT_DIR, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Generated by tools/generate_tables.py — do not edit by hand.\n")
        for line in header:
            f.write(f"# {line}\n")
        for row in rows:
            f.write("|".join(str(c) for c in row) + "\n")
    print(f"  {name}: {len(rows)} rows")
    return len(rows)


# ---------------------------------------------------------------- generators
def gen_species(repo, consts, dex, display, out):
    names = read_name_table(cparse.repo_path(repo, "src/data/text/species_names.h"), "gSpeciesNames")
    info = read_struct_table(cparse.repo_path(repo, "src/data/pokemon/species_info.h"), "gSpeciesInfo")
    ability_names = read_name_table(cparse.repo_path(repo, "src/data/text/abilities.h"), "gAbilityNames")

    # species internal id -> national number, in the order of sSpeciesToNationalPokedexNum
    nat_src = cparse.repo_path(repo, "src/pokemon.c")
    order = read_flat_list(nat_src, "sSpeciesToNationalPokedexNum[NUM_SPECIES - 1]")
    internal_to_national = {}
    for entry in order:
        m = re.fullmatch(r"SPECIES_TO_NATIONAL\((\w+)\)", entry)
        if not m:
            raise SystemExit(f"unexpected sSpeciesToNationalPokedexNum entry: {entry!r}")
        internal = consts[f"SPECIES_{m.group(1)}"]
        internal_to_national[internal] = dex[f"NATIONAL_DEX_{m.group(1)}"]

    rows = []
    for internal in sorted(internal_to_national):
        const = f"SPECIES_{_species_suffix(consts, internal)}"
        rec = info.get(const)
        if rec is None or not rec:
            continue
        base = [_int(consts, rec[k]) for k in ("baseHP", "baseAttack", "baseDefense",
                                               "baseSpeed", "baseSpAttack", "baseSpDefense")]
        types = [_int(consts, t) for t in _braced_list(rec["types"])]
        tnames = "/".join(dict.fromkeys(TYPE_NAMES[t] for t in types))
        gender = _gender_ratio(consts, rec["genderRatio"])
        growth = GROWTH_CODES[rec["growthRate"]]
        abil = [_int(consts, a) for a in _braced_list(rec["abilities"])]
        abil_names = []
        for a in abil:
            const_a = _ability_suffix(consts, a)
            abil_names.append("(none)" if a == consts["ABILITY_NONE"]
                              else display.name("abilities", const_a, ability_names[const_a]))
        if abil_names[1] in ("(none)", abil_names[0]):
            abil_names[1] = abil_names[0]
        rows.append([internal, internal_to_national[internal],
                     display.name("species", const, names[const]),
                     ",".join(str(b) for b in base), tnames, gender, growth, "/".join(abil_names)])
    out["species"] = write_table("species.txt", [
        "internal id|national dex|name|base hp,atk,def,spe,spa,spd|types|gender ratio|growth|ability1/ability2",
        "Sources: constants/species.h, constants/pokedex.h, src/pokemon.c (sSpeciesToNationalPokedexNum),",
        "         src/data/pokemon/species_info.h, src/data/text/species_names.h, src/data/text/abilities.h",
        "Gender ratio: 0 = always male, 254 = always female, 255 = genderless, else female threshold.",
        "Base stats are in the save's internal order (HP, Atk, Def, Spe, SpA, SpD)."], rows)
    return internal_to_national


def _species_suffix(consts, value):
    best = None
    for k, v in consts.items():
        if not k.startswith("SPECIES_") or v != value or k in ("SPECIES_NONE",):
            continue
        if best is None or (best.startswith("SPECIES_OLD_UNOWN") and not k.startswith("SPECIES_OLD_UNOWN")):
            best = k
    if best is None:
        raise SystemExit(f"no SPECIES_* constant has value {value}")
    return best[len("SPECIES_"):]


def _ability_suffix(consts, value):
    for k, v in consts.items():
        if k.startswith("ABILITY_") and v == value and k != "ABILITIES_COUNT":
            return k
    raise SystemExit(f"no ABILITY_* constant has value {value}")


def _gender_ratio(consts, expr):
    m = re.fullmatch(r"PERCENT_FEMALE\(([\d.]+)\)", expr.strip())
    if m:
        return min(254, int(float(m.group(1)) * 255) // 100)
    return _int(consts, expr)


def gen_moves(repo, consts, display, out):
    names = read_name_table(cparse.repo_path(repo, "src/data/text/move_names.h"), "gMoveNames")
    moves = read_struct_table(cparse.repo_path(repo, "src/data/battle_moves.h"), "gBattleMoves")
    rows = []
    for const, fields in moves.items():
        mid = consts[const]
        if mid == 0:
            continue
        rows.append([mid, display.name("moves", const, names[const]), _int(consts, fields["pp"])])
    rows.sort(key=lambda r: r[0])
    out["moves"] = write_table("moves.txt", [
        "move id|name|base PP",
        "Sources: constants/moves.h, src/data/battle_moves.h, src/data/text/move_names.h"], rows)


def gen_items(repo, consts, display, out):
    with open(cparse.repo_path(repo, "src/data/items.json"), encoding="utf-8") as f:
        items = json.load(f)["items"]
    tm_moves = read_flat_list(cparse.repo_path(repo, "src/data/party_menu.h"), "sTMHMMoves[TMHM_COUNT]")
    move_names = read_name_table(cparse.repo_path(repo, "src/data/text/move_names.h"), "gMoveNames")
    rows, tm_rows = [], []
    for item_id, it in enumerate(items):
        const = it["itemId"]
        if item_id and const == "ITEM_NONE":
            continue   # two unused slots between the HMs and the Kanto key items
        if const != "ITEM_NONE" and consts[const] != item_id:
            raise SystemExit(f"items.json index {item_id} is {const} but constants say {consts[const]}")
        name = display.name("items", const, it["english"])
        pocket = it["pocket"].replace("POCKET_", "").lower()
        rows.append([item_id, name, pocket])
    for tm_index, move_const in enumerate(tm_moves):
        item_id = consts["ITEM_TM01"] + tm_index
        tm_rows.append([tm_index, item_id, consts[move_const],
                        display.name("moves", move_const, move_names[move_const])])
    out["items"] = write_table("items.txt", [
        "item id|name|pocket",
        "Sources: src/data/items.json, constants/items.h",
        f"ITEMS_COUNT = {consts['ITEMS_COUNT']}. Pockets: items, medicine, key_items, held_items,",
        "poke_balls, tm_case, berry_pouch."], rows)
    out["tmhm"] = write_table("tmhm.txt", [
        "tm/hm index (0-based)|item id|move id|move name",
        "Sources: src/data/party_menu.h (sTMHMMoves), constants/items.h",
        "Index i is the bit position in SaveBlock1.bagPocket_TMHM and item ITEM_TM01 + i."], tm_rows)


def gen_mapsec(repo, consts, display, out):
    with open(cparse.repo_path(repo, "src/data/region_map/region_map_sections.json"), encoding="utf-8") as f:
        sections = json.load(f)["map_sections"]
    rows = []
    for sec in sections:
        const = sec["map_section"]
        rows.append([consts[const], display.name("mapsec", const, sec["name"])])
    rows.sort(key=lambda r: r[0])
    for value, label in [(consts["MAPSEC_NONE"], "(none)"),
                         (consts["METLOC_SPECIAL_EGG"], "Egg (special)"),
                         (consts["METLOC_IN_GAME_TRADE"], "In-game trade"),
                         (consts["METLOC_FATEFUL_ENCOUNTER"], "Fateful encounter (event)")]:
        if not any(r[0] == value for r in rows):
            rows.append([value, label])
    out["mapsec"] = write_table("mapsec.txt", [
        "map section id|name  (this is what a Pokémon's met location stores)",
        "Sources: constants/region_map_sections.h, src/data/region_map/region_map_sections.json"], rows)


MAP_LABEL_WORDS = {"SSANNE": "S.S. Anne", "SS": "S.S.", "POKEMON": "Pokémon", "MT": "Mt.",
                   "PC": "PC", "TV": "TV", "HQ": "HQ", "OF": "of", "AND": "and", "THE": "the",
                   "DIGLETTS": "Diglett's", "SEAGALLOP": "Seagallop", "NPC": "NPC"}
# Floor/room markers that must keep their original casing.
MAP_LABEL_KEEP = re.compile(r"B?\d+F|\d+[A-Z]?|[A-Z]\d+|ROOF|PH")


def map_label(const):
    """MAP_FUCHSIA_CITY_POKEMON_CENTER_1F -> 'Fuchsia City Pokémon Center 1F'."""
    words = []
    for w in const[len("MAP_"):].split("_"):
        if w in MAP_LABEL_WORDS:
            words.append(MAP_LABEL_WORDS[w])
        elif MAP_LABEL_KEEP.fullmatch(w):
            words.append(w)
        else:
            # ROUTE23 -> "Route 23", but leave 1F/B2F style markers alone
            m = re.fullmatch(r"([A-Z]{3,})(\d+)", w)
            if m:
                words.append(titlecase(m.group(1)))
                words.append(m.group(2))
            else:
                words.append(titlecase(w))
    return " ".join(words)


def gen_maps(repo, consts, out):
    maps_dir = cparse.repo_path(repo, "data/maps")
    by_const = {}
    for folder in sorted(os.listdir(maps_dir)):
        path = os.path.join(maps_dir, folder, "map.json")
        if not os.path.exists(path):
            continue
        with open(path, encoding="utf-8") as f:
            m = json.load(f)
        by_const[m["id"]] = (m.get("region_map_section", "MAPSEC_NONE"), m["name"])
    rows = []
    for const, (mapsec, folder) in by_const.items():
        if const not in consts:
            continue
        value = consts[const]
        rows.append([f"{value >> 8}.{value & 0xFF}", const[len("MAP_"):],
                     consts.get(mapsec, consts["MAPSEC_NONE"]), folder, map_label(const)])
    rows.sort(key=lambda r: (int(r[0].split(".")[0]), int(r[0].split(".")[1])))
    out["maps"] = write_table("maps.txt", [
        "group.number|map constant (without MAP_)|map section id|folder name in data/maps|readable name",
        "Sources: constants/map_groups.h, data/maps/*/map.json",
        "SaveBlock1.location stores mapGroup then mapNum, which is this group.number."], rows)


def gen_flags(repo, consts, out):
    rows = []
    for name, value in sorted(consts.items(), key=lambda kv: kv[1]):
        if not name.startswith("FLAG_") or name in ("FLAGS_COUNT",):
            continue
        if re.fullmatch(r"FLAG_0x[0-9A-Fa-f]+", name):
            continue       # unnamed placeholder flags carry no information
        if not 0 <= value < consts["FLAGS_COUNT"]:
            continue
        rows.append([f"0x{value:03X}", name])
    seen, uniq = set(), []
    for value, name in rows:
        if value in seen:
            continue
        seen.add(value)
        uniq.append([value, name])
    out["flags"] = write_table("flags.txt", [
        "flag id (hex)|constant name",
        "Source: constants/flags.h. Placeholder FLAG_0x... names are left out.",
        f"FLAGS_COUNT = 0x{consts['FLAGS_COUNT']:X}; trainer-defeated flags are "
        f"0x{consts['TRAINER_FLAGS_START']:03X}-0x{consts['TRAINER_FLAGS_END']:03X}; "
        f"system flags start at 0x{consts['SYS_FLAGS']:03X}."], uniq)


def gen_vars(repo, consts, out):
    rows = []
    for name, value in sorted(consts.items(), key=lambda kv: kv[1]):
        if not name.startswith("VAR_") or re.fullmatch(r"VAR_0x[0-9A-Fa-f]+", name):
            continue
        if not consts["VARS_START"] <= value <= consts["VARS_END"]:
            continue
        rows.append([f"0x{value:04X}", name])
    out["vars"] = write_table("vars.txt", [
        "var id (hex)|constant name",
        "Source: constants/vars.h. Placeholder VAR_0x... names are left out.",
        f"SaveBlock1.vars covers 0x{consts['VARS_START']:04X}-0x{consts['VARS_END']:04X}."], rows)


STAT_LABEL_WORDS = {"POKEMON": "Pokémon", "POKECENTER": "Poké Center", "POKEDEX": "Pokédex",
                    "POKEBLOCKS": "Pokéblocks", "HOF": "Hall of Fame", "DAYCARE": "Day Care",
                    "TV": "TV", "NUM": "", "RTC": "clock"}


def gen_game_stats(repo, consts, out):
    rows = []
    for name, value in sorted(consts.items(), key=lambda kv: kv[1]):
        if not name.startswith("GAME_STAT_") or name.startswith("GAME_STAT_COUNT"):
            continue
        parts = [STAT_LABEL_WORDS.get(w, titlecase(w)) for w in name[len("GAME_STAT_"):].split("_")]
        label = " ".join(p for p in parts if p)
        rows.append([value, name, label])
    out["game_stats"] = write_table("game_stats.txt", [
        "index|constant name|label",
        "Source: constants/game_stat.h",
        f"NUM_GAME_STATS = {consts['NUM_GAME_STATS']}, of which "
        f"{consts['NUM_USED_GAME_STATS']} are used."], rows)


def gen_evolutions(repo, consts, out):
    path = cparse.repo_path(repo, "src/data/pokemon/evolution.h")
    with open(path, encoding="utf-8") as f:
        text = cparse._strip_block_comments(f.read())
    start = text.index("gEvolutionTable")
    body = text[text.index("{", start):]
    rows = []
    for m in re.finditer(r"\[\s*(SPECIES_\w+)\s*\]\s*=\s*\{(.*?)\}\s*,\s*\n", body, re.S):
        frm = consts[m.group(1)]
        for evo in re.finditer(r"\{([^{}]*)\}", m.group(2)):
            parts = [p.strip() for p in evo.group(1).split(",")]
            if len(parts) < 3 or parts[0] in ("0", ""):
                continue
            method, param, target = parts[0], parts[1], parts[2]
            rows.append([frm, method[len("EVO_"):].lower(), _int(consts, param), consts[target]])
    rows.sort(key=lambda r: (r[0], r[3]))
    out["evolutions"] = write_table("evolutions.txt", [
        "from species (internal)|method|parameter|into species (internal)",
        "Source: src/data/pokemon/evolution.h",
        "method 'level' means the parameter is the level; 'item' means it is an item id."], rows)


def gen_extended_dex(repo, dex_consts, out):
    rows = []
    for name, value in sorted(dex_consts.items(), key=lambda kv: kv[1]):
        if not name.startswith("EXTENDED_DEX_") or name in ("EXTENDED_DEX_NONE", "EXTENDED_DEX_COUNT"):
            continue
        if value > dex_consts["EXTENDED_DEX_COUNT"]:
            continue
        rows.append([value, name[len("EXTENDED_DEX_"):]])
    out["extended_dex"] = write_table("extended_dex.txt", [
        "extended dex number|species constant suffix",
        "Source: constants/pokedex.h (EXTENDED_DEX_* up to EXTENDED_DEX_COUNT)",
        "FRLG+'s Extended Dex is every Pokémon obtainable in one copy of the game without trading."], rows)


def gen_encounters(repo, consts, out):
    path = cparse.repo_path(repo, "src/data/wild_encounters.h")
    with open(path, encoding="utf-8") as f:
        text = cparse._strip_block_comments(f.read())
    # sMapName_Version_MethodMons[] = { {min, max, SPECIES_X}, ... }
    tables = {}
    for m in re.finditer(r"const struct WildPokemon (s\w+)\[\]\s*=\s*\{", text):
        name = m.group(1)
        end = cparse._matching_brace(text, text.index("{", m.end() - 1))
        entries = []
        for row in re.finditer(r"\{\s*(\d+)\s*,\s*(\d+)\s*,\s*(SPECIES_\w+)\s*\}", text[m.end():end]):
            entries.append((int(row.group(1)), int(row.group(2)), consts[row.group(3)]))
        tables[name] = entries
    # info struct -> the WildPokemon table it points at
    info_to_table = {}
    for m in re.finditer(r"const struct WildPokemonInfo (s\w+)\s*=\s*\{\s*(\d+)\s*,\s*(s\w+)\s*\}", text):
        info_to_table[m.group(1)] = (int(m.group(2)), m.group(3))

    rows = []
    for row_text in read_array_entries(path, "gWildMonHeaders[]"):
        fields = dict(re.findall(r"\.(\w+)\s*=\s*([^,\n]+)", row_text))
        group = _map_part(consts, fields.get("mapGroup", ""))
        num = _map_part(consts, fields.get("mapNum", ""))
        if group is None or num is None:
            continue
        for key, value in fields.items():
            m = re.fullmatch(r"(land|water|rockSmash|fishing)MonsInfo_(FR|LG)", key)
            if not m:
                continue
            info = value.strip().lstrip("&")
            if info == "NULL" or info not in info_to_table:
                continue
            rate, table = info_to_table[info]
            method = {"land": "LandMons", "water": "WaterMons",
                      "rockSmash": "RockSmashMons", "fishing": "FishingMons"}[m.group(1)]
            seen = {}
            for lo, hi, species in tables.get(table, []):
                prev = seen.get(species)
                seen[species] = (min(lo, prev[0]), max(hi, prev[1])) if prev else (lo, hi)
            for species, (lo, hi) in seen.items():
                rows.append([species, m.group(2), f"{group}.{num}",
                             ENCOUNTER_METHODS[method], lo, hi, rate])
    rows.sort(key=lambda r: (r[0], r[1], r[2]))
    out["encounters"] = write_table("encounters.txt", [
        "species (internal)|version (FR/LG)|map group.number|method|min level|max level|encounter rate",
        "Source: src/data/wild_encounters.h (gWildMonHeaders and the tables it points at)",
        "One row per species per map per method; levels are the range over that method's slots."], rows)


def _map_part(consts, expr):
    m = re.fullmatch(r"MAP_(?:GROUP|NUM)\((\w+)\)", expr.strip())
    if not m:
        return None
    value = consts.get(f"MAP_{m.group(1)}")
    if value is None:
        return None
    return (value >> 8) if expr.strip().startswith("MAP_GROUP") else (value & 0xFF)


def gen_save_layout(repo, consts, out, game="frlgplus"):
    """The offsets the extractor uses, derived from include/global.h, as a table."""
    layout = compute_layout(repo, consts, game)
    rows = [[k, v, f"0x{v:X}"] for k, v in layout.items()]
    out["save_layout"] = write_table("save_layout.txt", [
        "name|value (decimal)|value (hex)",
        "Derived from include/global.h, include/constants/global.h, include/save.h and",
        "include/pokemon_storage_system.h by tools/generate_tables.py.",
        "Offsets are from the start of the named save block."], rows)
    return layout


def compute_layout(repo, consts, game="frlgplus"):
    """Walk the item block of SaveBlock1 so the pocket offsets come from the source."""
    g = cparse.repo_path(repo, "include/global.h")
    with open(g, encoding="utf-8") as f:
        text = f.read()   # keep the /*0x...*/ offset comments: they are what we read
    sb1 = text[text.index("struct SaveBlock1"):]
    sb1 = sb1[:cparse._matching_brace(sb1, sb1.index("{")) + 1]

    def annotated(field):
        m = re.search(r"/\*(0x[0-9A-Fa-f]+)\*/\s*[^;]*\b" + field + r"\b", sb1)
        if not m:
            raise SystemExit(f"no annotated offset for SaveBlock1.{field}")
        return int(m.group(1), 16)

    layout = {}
    layout["sb1_money"] = annotated("money")
    layout["sb1_coins"] = annotated("coins")
    layout["sb1_registered_item"] = annotated("registeredItem")
    off = annotated("pcItems")
    layout["sb1_pc_items"] = off
    layout["pc_items_count"] = consts["PC_ITEMS_COUNT"]
    off += 4 * consts["PC_ITEMS_COUNT"]
    if game == "vanilla":
        # Vanilla's pockets are five plain ItemSlot arrays in this order, and the
        # walk must land exactly on seen1 or the layout is wrong.
        for key, count_const, field in [("items", "BAG_ITEMS_COUNT", "bagPocket_Items"),
                                        ("key_items", "BAG_KEYITEMS_COUNT", "bagPocket_KeyItems"),
                                        ("poke_balls", "BAG_POKEBALLS_COUNT", "bagPocket_PokeBalls"),
                                        ("tmhm", "BAG_TMHM_COUNT", "bagPocket_TMHM"),
                                        ("berries", "BAG_BERRIES_COUNT", "bagPocket_Berries")]:
            # Vanilla annotates every pocket, so check each walked offset, not just the sum:
            # two swapped counts would still land on seen1 with wrong offsets in between.
            if off != annotated(field):
                raise SystemExit(f"vanilla bag walk put {key} at {off:#x} but SaveBlock1.{field} "
                                 f"is annotated at {annotated(field):#x}")
            layout[f"sb1_bag_{key}"] = off
            layout[f"bag_{key}_count"] = consts[count_const]
            off += 4 * consts[count_const]
        expected = annotated("seen1")
        if off != expected:
            raise SystemExit(
                f"vanilla bag walk ended at {off:#x} but seen1 is annotated at {expected:#x}")
    else:
        layout["sb1_bag_items"] = off
        layout["bag_items_count"] = consts["BAG_ITEMS_COUNT"]
        off += 4 * consts["BAG_ITEMS_COUNT"]
        layout["sb1_bag_poke_balls"] = off
        layout["bag_poke_balls_count"] = consts["BAG_POKEBALLS_COUNT"]
        off += 4 * consts["BAG_POKEBALLS_COUNT"]
        layout["sb1_bag_tmhm_bits"] = off
        layout["bag_tmhm_bytes"] = 8
        off += 8
        layout["sb1_bag_key_items"] = off
        layout["bag_key_items_count"] = consts["BAG_KEYITEMS_COUNT"]
        off += consts["BAG_KEYITEMS_COUNT"]
        off += off % 2                      # struct ItemSlot needs 2-byte alignment
        layout["sb1_bag_medicine"] = off
        layout["bag_medicine_count"] = consts["BAG_MEDICINE_COUNT"]
        off += 4 * consts["BAG_MEDICINE_COUNT"]
        layout["sb1_bag_held_items"] = off
        layout["bag_held_items_count"] = consts["BAG_HELD_ITEMS_COUNT"]
        off += 4 * consts["BAG_HELD_ITEMS_COUNT"]
        layout["sb1_item_block_end"] = off + 92     # leftoverItemSlots[92]
        if layout["sb1_item_block_end"] != annotated("seen1"):
            raise SystemExit(f"item block ends at 0x{layout['sb1_item_block_end']:X} but SaveBlock1.seen1 is "
                             f"annotated at 0x{annotated('seen1'):X} — the bag layout changed.")

        mg = annotated("mysteryGift")
        mystery_size = 0x36C
        off = mg + mystery_size + 176           # unused_348C[176]
        layout["sb1_nuzlocke_dupe_flags"] = off
        off += 52
        layout["sb1_bag_berries"] = off
        layout["bag_berries_count"] = consts["BAG_BERRIES_COUNT"]
        off += 4 * consts["BAG_BERRIES_COUNT"]
        if off != annotated("ramScript"):
            raise SystemExit(f"berry pocket ends at 0x{off:X} but SaveBlock1.ramScript is annotated at "
                             f"0x{annotated('ramScript'):X}.")

    layout["sb1_pos"] = annotated("pos")
    layout["sb1_location"] = annotated("location")
    layout["sb1_last_heal_location"] = annotated("lastHealLocation")
    layout["sb1_party_count"] = annotated("playerPartyCount")
    layout["sb1_party"] = annotated("playerParty")
    layout["sb1_flags"] = annotated("flags")
    layout["sb1_vars"] = annotated("vars")
    layout["sb1_game_stats"] = annotated("gameStats")
    daycare_mon_size = annotated("unused_3D24") - annotated("route5DayCareMon")
    if game == "vanilla":
        # The vanilla /*0x2F80*/ annotation on `daycare` is correct there.
        daycare = annotated("daycare")
    else:
        # The /*0x2F80*/ comment on `daycare` is a vanilla leftover: FRLG+ replaced
        # dewfordTrends[5] (40 bytes) with filler_EasyChatPairs[36], moving the Day Care
        # down by 4. Walk it instead and check it lands on giftRibbons.
        daycare = annotated("filler_oldMan") + 64 + 36
    # offspringPersonality is u16 in vanilla and u32 in FRLG+; read which from the source.
    m = re.search(r"struct DayCare\s*\{[^}]*?\bu(16|32)\s+offspringPersonality", text)
    if not m:
        raise SystemExit("cannot find the type of DayCare.offspringPersonality in include/global.h")
    offspring_size = int(m.group(1)) // 8
    daycare_end = daycare + 2 * daycare_mon_size + offspring_size + 1
    daycare_end += -daycare_end % 4
    if daycare_end != annotated("giftRibbons"):
        raise SystemExit(f"Day Care walk ends at 0x{daycare_end:X} but SaveBlock1.giftRibbons is "
                         f"annotated at 0x{annotated('giftRibbons'):X}.")
    layout["sb1_daycare"] = daycare
    layout["daycare_mon_size"] = daycare_mon_size
    layout["daycare_mon_count"] = consts["DAYCARE_MON_COUNT"]
    layout["sb1_daycare_offspring"] = daycare + 2 * daycare_mon_size
    layout["daycare_offspring_width"] = offspring_size
    layout["sb1_daycare_step_counter"] = daycare + 2 * daycare_mon_size + offspring_size
    layout["sb1_roamer"] = annotated("roamer")
    layout["roamer_size"] = annotated("enigmaBerry") - annotated("roamer")
    layout["sb1_rival_name"] = annotated("rivalName")
    layout["sb1_route5_daycare_mon"] = annotated("route5DayCareMon")
    if game != "vanilla":        # the Key System flags are an FRLG+ addition
        layout["sb1_last_viewed_pokedex_entry"] = annotated("lastViewedPokedexEntry")
        layout["sb1_key_flags"] = layout["sb1_last_viewed_pokedex_entry"] + 2
    if game != "vanilla":        # Master Trainers is an FRLG+ addition
        layout["sb1_master_trainer_title"] = annotated("filler_062C") + 5
        layout["sb1_master_trainer_flags"] = annotated("unused_3A94") + 44
    layout["num_flag_bytes"] = consts["FLAGS_COUNT"] // 8
    layout["flags_count"] = consts["FLAGS_COUNT"]
    layout["vars_count"] = consts["VARS_COUNT"]
    layout["vars_base"] = consts["VARS_START"]
    layout["num_game_stats"] = consts["NUM_GAME_STATS"]
    layout["trainer_flags_start"] = consts["TRAINER_FLAGS_START"]
    layout["trainer_flags_end"] = consts["TRAINER_FLAGS_END"]
    layout["sys_flags"] = consts["SYS_FLAGS"]
    layout["flag_badge01"] = consts["FLAG_BADGE01_GET"]

    sb2 = text[text.index("struct SaveBlock2"):]
    sb2 = sb2[:cparse._matching_brace(sb2, sb2.index("{")) + 1]

    def annotated2(field):
        m = re.search(r"/\*(0x[0-9A-Fa-f]+)\*/\s*[^;]*\b" + field + r"\b", sb2)
        if not m:
            raise SystemExit(f"no annotated offset for SaveBlock2.{field}")
        return int(m.group(1), 16)

    layout["sb2_player_name"] = annotated2("playerName")
    layout["sb2_player_gender"] = annotated2("playerGender")
    layout["sb2_trainer_id"] = annotated2("playerTrainerId")
    layout["sb2_play_time_hours"] = annotated2("playTimeHours")
    layout["sb2_play_time_minutes"] = annotated2("playTimeMinutes")
    layout["sb2_play_time_seconds"] = annotated2("playTimeSeconds")
    layout["sb2_options_button_mode"] = annotated2("optionsButtonMode")
    layout["sb2_options"] = annotated2("optionsTextSpeed")
    layout["sb2_encryption_key"] = annotated2("encryptionKey")
    dex_at = annotated2("pokedex")
    layout["sb2_pokedex"] = dex_at
    pk = text[text.index("struct Pokedex"):]
    pk = pk[:cparse._matching_brace(pk, pk.index("{")) + 1]
    owned = int(re.search(r"/\*(0x[0-9A-Fa-f]+)\*/\s*u8 owned", pk).group(1), 16)
    seen = int(re.search(r"/\*(0x[0-9A-Fa-f]+)\*/\s*u8 seen", pk).group(1), 16)
    layout["sb2_dex_owned"] = dex_at + owned
    layout["sb2_dex_seen"] = dex_at + seen
    layout["dex_flag_bytes"] = seen - owned

    ps = cparse.repo_path(repo, "include/pokemon_storage_system.h")
    with open(ps, encoding="utf-8") as f:
        pstext = f.read()
    layout["pc_boxes"] = 4            # u8 currentBox then 4-byte-aligned BoxPokemon array
    layout["pc_box_names"] = int(re.search(r"/\*(0x[0-9A-Fa-f]+)\*/\s*u8 boxNames", pstext).group(1), 16)
    layout["pc_box_wallpapers"] = int(
        re.search(r"/\*(0x[0-9A-Fa-f]+)\*/\s*u8 boxWallpapers", pstext).group(1), 16)
    layout["total_boxes"] = _hdef(pstext, "TOTAL_BOXES_COUNT")
    layout["in_box_count"] = _hdef(pstext, "IN_BOX_ROWS") * _hdef(pstext, "IN_BOX_COLUMNS")
    layout["box_name_length"] = _hdef(pstext, "BOX_NAME_LENGTH")
    layout["pc_end"] = layout["pc_box_wallpapers"] + layout["total_boxes"]

    sv = cparse.repo_path(repo, "include/save.h")
    with open(sv, encoding="utf-8") as f:
        svtext = f.read()
    layout["sector_data_size"] = _hdef(svtext, "SECTOR_DATA_SIZE")
    layout["sectors_per_slot"] = _hdef(svtext, "NUM_SECTORS_PER_SLOT")
    layout["sector_id_hof_1"] = _hdef(svtext, "SECTOR_ID_HOF_1")
    layout["items_count"] = consts["ITEMS_COUNT"]
    layout["item_tm01"] = consts["ITEM_TM01"]
    if game != "vanilla":        # the Link Bracelet is an FRLG+ item
        layout["item_link_bracelet"] = consts["ITEM_LINK_BRACELET"]
    layout["tmhm_count"] = consts["BAG_TMHM_COUNT"]
    layout["num_species"] = consts["NUM_SPECIES"]
    return layout


def _hdef(text, name):
    m = re.search(r"#define\s+" + name + r"\s+(\S+)", text)
    return int(m.group(1), 0)


def _braced_list(expr):
    inner = expr.strip()
    if inner.startswith("{"):
        inner = inner[1:inner.rindex("}")]
    return [p.strip() for p in inner.split(",") if p.strip()]


def _int(consts, expr):
    v = consts.evaluate(expr)
    if v is None:
        raise SystemExit(f"cannot evaluate {expr!r}")
    return v


# ---------------------------------------------------------------- key items
def gen_key_item_indices(repo, consts, out):
    """FRLG+ stores key items as one-byte indices; recover the mapping from item.c."""
    src = cparse.repo_path(repo, "src/item.c")
    with open(src, encoding="utf-8") as f:
        text = cparse._strip_block_comments(f.read())
    body = text[text.index("void DeserializeKeyItemSlots"):]
    body = body[:body.index("\nvoid ", 1)]

    # Each branch looks like:  if (<range test on bagPocket_KeyItems[i]>) AddBagItem(<expr>, 1);
    branches = []
    for m in re.finditer(r"if\s*\((.*?)\)\s*\n?\s*AddBagItem\(([^;]+?),\s*1\)\s*;", body, re.S):
        cond, arg = m.group(1), m.group(2).strip()
        tests = re.findall(r"bagPocket_KeyItems\[i\]\s*(<=|>=|==|<|>)\s*(\d+)", cond)
        lo, hi = 1, 255
        for op, num in tests:
            num = int(num)
            if op == "<=":
                hi = min(hi, num)
            elif op == "<":
                hi = min(hi, num - 1)
            elif op == ">=":
                lo = max(lo, num)
            elif op == ">":
                lo = max(lo, num + 1)
            elif op == "==":
                lo = hi = num
        if arg.startswith("gSaveBlock1Ptr"):
            shift = consts.evaluate("0 " + arg.split("]", 1)[1].strip())
            if shift is None:
                raise SystemExit(f"cannot read the key-item offset from {arg!r}")
            branches.append((lo, hi, "offset", shift))
        else:
            branches.append((lo, hi, "fixed", consts[arg]))
    if not branches:
        raise SystemExit("DeserializeKeyItemSlots no longer has recognisable AddBagItem branches")

    rows = []
    for lo, hi, kind, value in branches:
        for idx in range(lo, hi + 1):
            rows.append([idx, value + idx if kind == "offset" else value])
    rows.sort(key=lambda r: r[0])
    seen = set()
    rows = [r for r in rows if not (r[0] in seen or seen.add(r[0]))]
    bad = [r for r in rows if not 1 <= r[1] < consts["ITEMS_COUNT"]]
    if bad:
        raise SystemExit(f"key-item decode produced item ids outside 1..{consts['ITEMS_COUNT'] - 1}: {bad[:5]}")
    out["key_item_indices"] = write_table("key_item_indices.txt", [
        "stored byte|item id",
        "Source: src/item.c (DeserializeKeyItemSlots)",
        "FRLG+ shrank the Key Items pocket to one byte per slot; this is the decode table."], rows)


def _repo_commit(repo):
    """The source checkout's short commit, or None when it is not a git clone.

    Recorded instead of the checkout's path: the path says where one person
    keeps their files, the commit says which version of FRLG+ the tables
    describe — which is the part anyone reading them needs.
    """
    try:
        import subprocess
        out = subprocess.run(["git", "-C", repo, "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True, timeout=10)
        return out.stdout.strip() or None if out.returncode == 0 else None
    except Exception:
        return None


# ---------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--game", choices=["frlgplus", "vanilla"], default="frlgplus",
                    help="which tree --repo points at (default: frlgplus)")
    ap.add_argument("--repo", required=True,
                    help="checkout of Deokishisu/FRLG-Plus, or of pret/pokefirered for --game vanilla")
    args = ap.parse_args()
    repo = os.path.abspath(args.repo)
    for rel in REQUIRED[args.game]:
        if not os.path.isfile(os.path.join(repo, rel)):
            raise SystemExit(f"{repo} is missing {rel}, which --game {args.game} needs")
    global OUT_DIR
    OUT_DIR = DATA_DIR if args.game == "frlgplus" else os.path.join(DATA_DIR, "vanilla")

    consts = Consts()
    for rel in ["include/constants/global.h", "include/constants/species.h", "include/constants/items.h",
                "include/constants/moves.h", "include/constants/abilities.h",
                "include/constants/pokemon.h", "include/constants/game_stat.h",
                "include/constants/region_map_sections.h", "include/constants/map_groups.h",
                "include/constants/trainers.h", "include/constants/opponents.h",
                "include/constants/vars.h",
                "include/constants/flags.h", "include/party_menu.h"]:
        path = os.path.join(repo, rel)
        if not os.path.isfile(path):
            if args.game == "vanilla":
                continue        # build-generated in the vanilla decomp; not needed for the layout
            raise SystemExit(f"{repo} is missing {rel}")
        consts.load_defines(path)
    dex = Consts()
    if args.game == "frlgplus":      # only the name tables use the Pokedex constants
        dex.load_enum(cparse.repo_path(repo, "include/constants/pokedex.h"), "NATIONAL_DEX_NONE")
        dex.load_enum(cparse.repo_path(repo, "include/constants/pokedex.h"), "EXTENDED_DEX_NONE")
        dex.load_defines(cparse.repo_path(repo, "include/constants/pokedex.h"))

    display = Display(os.path.join(TOOLS_DIR, "display_names.json"))
    os.makedirs(OUT_DIR, exist_ok=True)
    print(f"generating tables from {repo}")
    out = {}
    if args.game == "frlgplus":
        gen_species(repo, consts, dex, display, out)
        gen_moves(repo, consts, display, out)
        gen_items(repo, consts, display, out)
        gen_mapsec(repo, consts, display, out)
        gen_maps(repo, consts, out)
        gen_flags(repo, consts, out)
        gen_vars(repo, consts, out)
        gen_game_stats(repo, consts, out)
        gen_evolutions(repo, consts, out)
        gen_extended_dex(repo, dex, out)
        gen_encounters(repo, consts, out)
        gen_key_item_indices(repo, consts, out)
    layout = gen_save_layout(repo, consts, out, args.game)

    unused = display.unused() if args.game == "frlgplus" else []
    if unused:
        print("  note: unused display_names.json entries: " + ", ".join(unused))
    stamp = {"generated_at": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
             "repo_name": os.path.basename(repo.rstrip(os.sep)), "repo_commit": _repo_commit(repo),
             "rows": out,
             "save_layout": {k: (f"0x{v:X}" if isinstance(v, int) else v) for k, v in layout.items()}}
    with open(os.path.join(OUT_DIR, "generated.json"), "w", encoding="utf-8") as f:
        json.dump(stamp, f, ensure_ascii=False, indent=1)
    print("done")


if __name__ == "__main__":
    main()
